# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$latestdocker = <<SCRIPT
sudo yum update -y
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce 
sudo systemctl restart docker
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "node0" do |node0|
    node0.vm.box = "williamyeh/centos7-docker"
    node0.vm.hostname = "node-0"
    
    node0.vm.network "private_network",
      ip:"10.1.1.1",
      use_dhcp_assigned_default_route: true
    
    node0.vm.provision "shell", inline: $latestdocker

    node0.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node-0"]
    end
  end
  config.vm.define "node1" do |node1|
    node1.vm.box = "williamyeh/centos7-docker"
    node1.vm.hostname = "node-1"

    node1.vm.network "private_network",
      ip:"10.1.1.2",
      use_dhcp_assigned_default_route: true

    node1.vm.provision "shell", inline: $latestdocker

    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node-1"]
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.box = "williamyeh/centos7-docker"
    node2.vm.hostname = "node-2"

    node2.vm.network "private_network",
      ip:"10.1.1.3",
      use_dhcp_assigned_default_route: true

    node2.vm.provision "shell", inline: $latestdocker

    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node-2"]
    end
  end
  config.vm.define "node3" do |node3|
    node3.vm.box = "williamyeh/centos7-docker"
    node3.vm.hostname = "node-3"

    node3.vm.network "private_network",
      ip:"10.1.1.4",
      use_dhcp_assigned_default_route: true
      
    node3.vm.provision "shell", inline: $latestdocker

    node3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node-3"]
    end
  end

end
